#!/bin/bash
# XFCE DCV session with alternative window manager

# Set locale to avoid warnings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Set background
xsetroot -solid grey

# Disable thumbnail generation for faster file browser
export TUMBLER_DISABLE=1

# Start Nautilus daemon for instant file browser launches
nautilus --no-desktop &

# Use metacity as window manager (more stable in containers than xfwm4)
metacity --replace &

# Wait for WM
sleep 1

# Start XFCE panel (with --disable-wm-check since we're using metacity)
xfce4-panel --disable-wm-check &

# Start desktop (with --disable-wm-check)
xfdesktop --disable-wm-check &

# Start terminal
xfce4-terminal --maximize &

# Keep session alive
wait
